package com.example.common

//Shared pref:
const val SHARED_PREF_NAME = "TİCARİ_MULTİKOPTER_SHARED_PREF"
const val SHARED_PREF_FILE_PERMISSION_SEEN = "TİCARİ_MULTİKOPTER_SHARED_FILE_PERMISSION_SEEN"

//Intent:
const val INTENT_ERROR_DIALOG_BUTTON_TEXT = "INTENT_ERROR_DIALOG_BUTTON_TEXT"
const val INTENT_ERROR_DIALOG_DESCRIPTION = "INTENT_ERROR_DIALOG_TITLE"
const val FILE_ACTION_REQUEST_CODE = 1002
const val DRAW_OVERLAY_REQUEST_CODE = 1003